### ISSUE TITLE
Do a general cleanup refactoring before release

### ISSUE THREAD

**Issue by indiejames** [indiejames/vscode-clojure-debug#36]
Need to clean up the code base.
- refactor common code into new namespaces
- standardize messages
- remove unnecessary output
- standardize coding style for Typescript code

**Comment by jasongilman** [comment]
Are you getting close to release? That's exciting!

**Comment by indiejames** [comment]
I wouldn't say close :). I just added that issue to remind me to do it
before I release. I'm trying to get some work in this weekend, but
realistically I don't think I will reach a 1.0 release until August with
all the other things I have going on. On the other hand I just found out
you can mark your extension  as a "preview" in the VS Code extension
marketplace, so I may do a preview release early to get feedback.

**Comment by indiejames** [comment]
Need to take a look at the state logic used by the debug adapter to clean it up or maybe remove it altogether.
