### ISSUE TITLE
how to install this extension?

### ISSUE THREAD

**Issue by feng5** [indiejames/vscode-clojure-debug#50]
im new to vscode and want to know how to install this extension? it seems that it is not yet realese to marketplace.
thanks

**Comment by indiejames** [comment]
This extension is not available yet. I hope to issue a preview release in August.

**Comment by phungleson** [comment]
Is there anyway to install it without going through marketplace?

**Comment by indiejames** [comment]
You could clone the repo and side load it by following the directions here https://code.visualstudio.com/Docs/extensions/install-extension, but recommend waiting a bit as things are still in flux and might not be working correctly at any given time.

**Comment by chrisdavies** [comment]
Bump. This looks like a great extension. It still doesn't seem to show up when I search for "Continuum". Is it still necessary to side-load, or is it under a different name, now?

**Comment by indiejames** [comment]
I have not released it to the VS Code market place yet. I will release a preview (mac only) version this weekend. There are a couple of show-stopper bugs on Windows and I have not tested it at all on Linux yet.

**Comment by indiejames** [comment]
The preview release went out last week. You should be able to load via the marketplace now.
